### ISSUE TITLE
Bug after editing script

### ISSUE THREAD

**Issue by Mr-Pine** [DaKie206/Karambolage-3D#36]
![image](https://user-images.githubusercontent.com/50425705/75680832-ab787400-5c92-11ea-8c15-6c89d7342329.png)

**Comment by Mr-Pine** [comment]
![image](https://user-images.githubusercontent.com/50425705/75685756-63aa1a80-5c9b-11ea-9edd-805476879b8c.png)

**Comment by Mr-Pine** [comment]
Nope. Noch da

**Comment by Mister-Muffin** [comment]
Hast du in den Projekt Einstellungen Input System "Both" ausgewählt?
