### ISSUE TITLE
Crash when shooting enemy

### ISSUE THREAD

**Issue by Mister-Muffin** [DaKie206/Karambolage-3D#37]
![grafik](https://user-images.githubusercontent.com/45641704/75687599-52164200-5c9e-11ea-8f3b-5689004da7ed.png)

**Comment by Mr-Pine** [comment]
Bei mir noch nicht. Hab auch noch nicht geupdated

**Comment by Mister-Muffin** [comment]
Bei mir auch nicht mehr...
Keine Ahnung was das war
